<?xml version="1.0"?>
<package format="3">
  <name>hu501urdf</name>
  <version>1.0.0</version>
  <description>hu501 USV model for VRX simulation</description>
  <maintainer email="anxie@todo.todo">anxie</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>